baseURL = "https://avhb.github.io/"
languageCode = "en"
title = "Arne Vanheesbeke"
theme = "hugo-coder"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Arne Vanheesbeke"
description = "Arne Vanheesbeke's personal website"
keywords = "blog,personal,testing,qa"
info = ["Test Engineer"]
avatarURL = "images/avatar.jpg"
dateFormat = "2006-01-02"
since = 2022
# Specify light/dark colorscheme
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/avhb/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/arne_vhb"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/arne-vanheesbeke-066057197"

# ---

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 4
url = "blog/"

# homelab content
# testing content

[[languages.en.menu.main]]
name = "Awesome Lists (curated by me)"
weight = 5
url = "lists/"
